### ISSUE TITLE
Grafana 10 needs new defaults behind reverse proxies

### ISSUE THREAD

**Issue by jstark1** [ConSol/omd-labs-docker#35]
the grafana update in omd 5.30 to version 10.2.3 needs "serve_from_sub_path = false" behind a reverse proxy.
see https://github.com/grafana/grafana/issues/70110
this should be the default, at lease in containers.

**Comment by sni** [comment]
hmm, i tested this after the update and in my setup, it was required to keep it to `true`. I just tested the omd v5.30 tag and it also works. And using a reverse proxy is the default setup for OMD. I don't think it is because of containers.
How does your setup looks like?

**Comment by jstark1** [comment]
I use haproxy for TLS termination, and redirect "/&lt;site&gt;" to the omd container. With v5.20 everything works, in v5.30 only grafana ends in an redirect loop.

**Comment by sni** [comment]
there are some scenarios here https://github.com/sni/Thruk/tree/master/t/scenarios
All of them use the labs docker container and some have a loadbalancer, ex.: the cluster_* ones. But i changed them a couple of weeks ago to use traefik instead of haproxy.
Somehow they work pretty well with `serve_from_sub_path = true`

**Comment by jstark1** [comment]
The docs https://github.com/grafana/grafana/blob/main/docs/sources/tutorials/run-grafana-behind-a-proxy/index.md does not contain infos about the apache reverse proxy used in the container. As far as i understand should serve_from_sub_path = true only be used when the proxy does not the rewrite of the path.
In my setup haproxy does no rewrite, and the container apache does via "ProxyPassReverse". Am i write?

**Comment by sni** [comment]
tbh, i haven't looked to deep into this setting since it works well in all our scenarios. Except one customer had an issue in his enterprise grafana so i didn't bother as well.
OMD itself does no path rewrite, the main system apache simply uses mod_proxy to proxy /site/.
But hey, if `serve_from_sub_path = false` works in your case, then great.
For now i don't think we will change the default here.

**Comment by jstark1** [comment]
All right, it's ok for me
